ALTER TABLE users ADD COLUMN show_first_name INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN show_last_name INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN show_age INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN show_sex INTEGER NOT NULL DEFAULT 1;
